export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    scansPerMonth: 5,
    aiSuggestions: true,
    aiRewritesPerMonth: 3,
    allowedBreakdowns: ['keywordMatch', 'sectionCompleteness', 'lengthDensity', 'compatibility'],
    features: [
      '5 scans/month',
      '3 AI rewrites/month',
      'ATS compatibility score',
      'Keyword match analysis',
      'Section completeness check',
      'Missing keyword report',
      'Scan history (last 10)',
    ],
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    price: 149,
    scansPerMonth: -1,
    aiSuggestions: true,
    aiRewritesPerMonth: -1,
    popular: true,
    allowedBreakdowns: ['keywordMatch', 'sectionCompleteness', 'lengthDensity', 'compatibility', 'formatting', 'impactMetrics'],
    features: [
      'Unlimited scans',
      'Unlimited AI rewrites',
      'All 6 ATS breakdown categories',
      'AI summary rewriter',
      'ATS format checker',
      'Impact & metrics scoring',
      'Export PDF reports',
      'Full scan history',
      'Email support',
    ],
  },
  teams: {
    id: 'teams',
    name: 'Teams',
    price: 499,
    scansPerMonth: -1,
    aiSuggestions: true,
    aiRewritesPerMonth: -1,
    allowedBreakdowns: ['keywordMatch', 'sectionCompleteness', 'lengthDensity', 'compatibility', 'formatting', 'impactMetrics'],
    features: [
      'Everything in Pro',
      'Team workspace (up to 5 seats)',
      'Bulk scanning (10 resumes/batch)',
      'Team analytics dashboard',
      'Shared scan history',
      'CSV/Excel export',
      'Priority email + chat support',
    ],
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    price: 1499,
    scansPerMonth: -1,
    aiSuggestions: true,
    aiRewritesPerMonth: -1,
    allowedBreakdowns: ['keywordMatch', 'sectionCompleteness', 'lengthDensity', 'compatibility', 'formatting', 'impactMetrics'],
    features: [
      'Everything in Teams',
      'Up to 25 team seats',
      'Bulk scanning (50 resumes/batch)',
      'Developer REST API (10K calls/mo)',
      'Custom company branding',
      'Webhook integrations',
      'Dedicated account manager',
      'Invoice billing',
    ],
  },
};

export const ATS_CRITERIA = {
  keywordMatch: { name: 'Keyword Match', weight: 0.3, icon: '🔑' },
  sectionCompleteness: { name: 'Section Completeness', weight: 0.2, icon: '📋' },
  formatting: { name: 'ATS Formatting', weight: 0.15, icon: '📄' },
  impactMetrics: { name: 'Impact & Metrics', weight: 0.15, icon: '📊' },
  lengthDensity: { name: 'Length & Density', weight: 0.1, icon: '📏' },
  compatibility: { name: 'ATS Compatibility', weight: 0.1, icon: '✅' },
};
